### ISSUE TITLE
About new Cryptography specification

### ISSUE THREAD

**Issue by loretoparisi** [gretelai/contact-tracing-experiment#1]
Hello, 
first of all thank you for this amazing experiment! I have authored a Colab Notebook with a simple input to change the input parameters. See [here](https://github.com/loretoparisi/contacttracing).
Apple and Google changed the cryptography specification few days ago introducing AES-128 (instead of HMAC) and removed the Tracing Key with a "Temporary Exposure Key".
Do you think to update this simulation with this new specification?

Thank you!.

**Comment by johntmyers** [comment]
Thanks for the feedback and the update on the specification. I'll look to update the current implementation to get close to matching.

**Comment by johntmyers** [comment]
I updated the changes in #2.  I did not implement the AEMK or the AEM as it's not quite clear what metadata is being encrypted and passed with the bluetooth beacon. I also don't think it is necessary for the simulation.

**Comment by loretoparisi** [comment]
Amazing! Yes it makes sense they have just specified _in order to encrypt additional metadata_, so it's not necessary here. Cool I will update the Colab!
